{{- range $name, $values := $.Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl $name $ }}
  labels:
    {{- include "helm_chart.labels" $ | nindent 4 }}
type: {{ $values.type }}
data:
  {{- range $k, $v := $values.data }}
  {{ $k }}: | 
{{ regexReplaceAllLiteral "\u0026#x3D;" (regexReplaceAllLiteral "\u0026#x2F;" (tpl $v $) "/") "=" | indent 4 }}
  {{- end }}
{{- end }}
