host: scilog.development.psi.ch

ingress:
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0

config: |
  {
    "lbBaseURL": "https://scilog.development.psi.ch/api/v1/",
    "help": "https://paulscherrerinstitute.github.io/scilog/",
    "oAuth2Endpoint": {
        "authURL": "auth/keycloak",
        "displayText": "PSI account",
        "toolTipText": "...like any normal user, including e-accounts, connected to your identity management system. Note that you may be redirected to an identity provider"
    }
  }
