host: scilog.psi.ch

config: |
  {
    "lbBaseURL": "https://scilog.psi.ch/api/v1/",
    "help": "https://paulscherrerinstitute.github.io/scilog/",
    "oAuth2Endpoint": {
      "authURL": "auth/keycloak",
      "displayText": "PSI account",
        "toolTipText": "...like any normal user, including e-accounts, connected to your identity management system. Note that you may be redirected to an identity provider"
    }

  }
