replicaCount: 1

image:
  repository: "{{ .Values.ciRepository }}"
  pullPolicy: Always
  tag: "{{ .Values.ciTag }}"

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: "{{ .Values.host }}"
      paths: 
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - "{{ .Values.host }}"
      secretName: "scilog-certificate"

configMaps: 
  "{{ .Release.Name }}-cm":
    config.json: "{{ .Values.config | indent 4 }}"
    
volumes:
  - name: config-volume
    configMap:
      name: "{{ .Release.Name }}-cm"

volumeMounts:
  - name: config-volume
    mountPath: /usr/share/nginx/html/assets/config.json
    subPath: config.json
