replicaCount: 1

image:
  repository: "{{ .Values.ciRepository }}"
  pullPolicy: Always
  tag: "{{ .Values.ciTag }}"

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
  probePath: /api/v1

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  hosts:
    - host: "{{ .Values.host }}"
      paths: 
        - path: /api
          pathType: Prefix
  tls:
    - hosts:
      - "{{ .Values.host }}"
      secretName: "scilog-certificate"

volumes:
  - name: secrets-volume
    secret:
      secretName: "{{ .Release.Name }}-s"

secrets: 
  "{{ .Release.Name }}-s":
    type: Opaque
    data: 
      datasource.json: '${{ secrets.DATASOURCE }}'
      oidc.json: '${{ secrets.OIDC }}'
      functionalAccounts.json: '${{ secrets.FUNCTIONAL_ACCOUNTS }}'
      jwt_secret: '${{ secrets.JWT_SECRET }}'

env:
  - name: BASE_PATH
    value: /api/v1
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef: 
        name: "{{ .Release.Name }}-s"
        key: jwt_secret

volumeMounts:
  - name: secrets-volume
    mountPath: /home/node/app/datasource.json
    subPath: datasource.json
  - name: secrets-volume
    mountPath: /home/node/app/oidc.json
    subPath: oidc.json
  - name: secrets-volume
    mountPath: /home/node/app/functionalAccounts.json
    subPath: functionalAccounts.json
