image:
  repository: "{{ .Values.ciRepository }}"
  pullPolicy: Always
  tag: "{{ .Values.ciTag }}"

secrets: 
  "{{ .Release.Name }}-s":
    type: Opaque
    data: 
      .env: '${{ secrets.PSYNC_ENV }}'

volumes:
  - name: secrets-volume
    secret:
      secretName: "{{ .Release.Name }}-s"
  - name: config-volume
    configMap:
      name: "{{ .Release.Name }}-cm"

volumeMounts:
  - name: secrets-volume
    mountPath: /usr/src/app/.env
    subPath: .env
  - name: config-volume
    mountPath: /usr/src/app/default_logbook_icon.jpg
    subPath: default_logbook_icon.jpg


configMaps: 
  "{{ .Release.Name }}-cm":
    default_logbook_icon.jpg: "{{ .Values.ciVars.SCILOG_DEFAULT_LOGBOOK_ICON }}"
