name: fe

on:  
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:

  set_env: 
    uses: paulscherrerinstitute/scicat-ci/.github/workflows/reusable.environment.yml@main

  check_changed:
    needs: set_env
    uses: paulscherrerinstitute/scicat-ci/.github/workflows/reusable.changes.yml@main
    with: 
      files: | 
        .github/workflows/fe.yml
        helm_configs/frontend/${{ needs.set_env.outputs.environment }}/**
        helm_configs/frontend/values.yaml
        scilog/scilog/**

  build_deploy:
    if: (needs.check_changed.outputs.changed == 'true' && !needs.set_env.outputs.component) || needs.set_env.outputs.component == 'fe'
    needs: 
     - check_changed
     - set_env
    uses: paulscherrerinstitute/scicat-ci/.github/workflows/reusable.build-deploy-scicat-component.yml@main
    with: 
      context: scilog/scilog/.
      image_name: ${{ github.repository }}/fe
      release_name: frontend
      namespace_prefix: scilog-
      tag: ${{ needs.set_env.outputs.tag }}
      environment: ${{ needs.set_env.outputs.environment }}
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      JSON_SECRETS: ${{ toJSON(secrets) }}
