name: fe

on:  
  workflow_dispatch: 
    inputs:
      submodule_commit:
        description: 'Commit of the submodule to deploy'     
        required: false
      commit: 
        description: 'Commit of the CI repo to deploy'     
        required: false
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:

  set_env: 
    uses: paulscherrerinstitute/scicat-ci/.github/workflows/reusable.environment.yml@main
    with: 
      commit: ${{ github.event.inputs.commit }}
      submodule_commit: ${{ github.event.inputs.submodule_commit }}

  check_changed:
    needs: set_env
    uses: paulscherrerinstitute/scicat-ci/.github/workflows/reusable.changes.yml@main
    with: 
      files: | 
        .github/workflows/fe.yml
        helm/configs/frontend/${{ needs.set_env.outputs.environment }}/**
        helm/configs/frontend/values.yaml
        scilog/scilog/**
      commit: ${{ needs.set_env.outputs.commit }}
      submodule_commit: ${{ github.event.inputs.submodule_commit }}
      submodule: scilog

  build_deploy:
    if: (needs.check_changed.outputs.changed == 'true' && !needs.set_env.outputs.component) || needs.set_env.outputs.component == 'fe'
    needs: 
     - check_changed
     - set_env
    uses: paulscherrerinstitute/scicat-ci/.github/workflows/reusable.build-deploy.yml@bastion_ssh
    with: 
      context: scilog/scilog/.
      image_name: ${{ github.repository }}/fe
      release_name: frontend
      namespace_prefix: scilog-
      tag: ${{ needs.set_env.outputs.tag }}
      environment: ${{ needs.set_env.outputs.environment }}
      commit: ${{ needs.set_env.outputs.commit }}
      submodule_commit: ${{ github.event.inputs.submodule_commit }}
      submodule: scilog
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      BASTION_USER: ${{ secrets.BASTION_USER }}
      BASTION_SSH_KEY: ${{ secrets.BASTION_SSH_KEY }}
