name: proposal-sync

on:  
  workflow_dispatch: 
    inputs:
      submodule_commit:
        description: 'Commit of the submodule to deploy'     
        required: false
      commit: 
        description: 'Commit of the CI repo to deploy'     
        required: false
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:

  set_env: 
    uses: paulscherrerinstitute/scicat-ci/.github/workflows/reusable.environment.yml@main
    with: 
      commit: ${{ github.event.inputs.commit }}
      submodule_commit: ${{ github.event.inputs.submodule_commit }}

  check_changed:
    needs: set_env
    uses: paulscherrerinstitute/scicat-ci/.github/workflows/reusable.changes.yml@main
    with: 
      files: | 
        .github/workflows/proposal-sync.yml
        helm_configs/proposal-sync/${{ needs.set_env.outputs.environment }}/**
        helm_configs/proposal-sync/values.yaml
        scilog/sdk/python/**
        scilog/importTools/**
      commit: ${{ needs.set_env.outputs.commit }}
      submodule_commit: ${{ github.event.inputs.submodule_commit }}
      submodule: scilog

  set_ci_vars:
    if: (needs.check_changed.outputs.changed == 'true' && !needs.set_env.outputs.component) || needs.set_env.outputs.component == 'ps'
    runs-on: ubuntu-latest
    needs: 
      - check_changed
      - set_env
    outputs:
      ciVars: ${{ steps.helm_vars.outputs.ciVars }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        ref: ${{ needs.set_env.outputs.commit }}

    - name: Set helm vars
      id: helm_vars
      run: |
        ciVars=$(cat <<EOF
          {
            "SCILOG_DEFAULT_LOGBOOK_ICON": $(jq -R -s < helm_configs/proposal-sync/default_logbook_icon.jpg)
          }
        EOF
        )
        echo "::set-output name=ciVars::$(echo $ciVars)"

  build_deploy:
    if: (needs.check_changed.outputs.changed == 'true' && !needs.set_env.outputs.component) || needs.set_env.outputs.component == 'ps'
    needs: 
     - check_changed
     - set_env
     - set_ci_vars
    uses: paulscherrerinstitute/scicat-ci/.github/workflows/reusable.build-deploy.yml@main
    with: 
      context: scilog/importTools/.
      image_name: ${{ github.repository }}/proposal-sync
      release_name: proposal-sync
      namespace_prefix: scilog-
      tag: ${{ needs.set_env.outputs.tag }}
      helm_ci_vars: ${{ needs.set_ci_vars.outputs.ciVars }}
      environment: ${{ needs.set_env.outputs.environment }}
      helm_chart: cron_chart
      commit: ${{ needs.set_env.outputs.commit }}
      submodule_commit: ${{ github.event.inputs.submodule_commit }}
      submodule: scilog
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      JSON_SECRETS: ${{ toJSON(secrets) }}
