name: proposal-sync

on:  
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  proposal-sync:
    name: proposal-sync
    steps:
    - name: set_env
      uses: paulscherrerinstitute/scicat-ci/.github/workflows/reusable.environment.yml@main
    - name: check_changed
      uses: paulscherrerinstitute/scicat-ci/.github/workflows/reusable.changes.yml@main
      with: 
        files: | 
          .github/workflows/proposal-sync.yml
          helm_configs/proposal-sync/${{ steps.set_env.outputs.environment }}/**
          helm_configs/proposal-sync/values.yaml
          scilog/sdk/python/**
          scilog/importTools/**

    - name: build_deploy
      if: (steps.check_changed.outputs.changed == 'true' && !steps.set_env.outputs.component) || steps.set_env.outputs.component == 'ps'
      uses: paulscherrerinstitute/scicat-ci/.github/workflows/reusable.build-deploy-scicat-component.yml@main
      with: 
        context: scilog/importTools/.
        image_name: ${{ github.repository }}/proposal-sync
        release_name: proposal-sync
        namespace_prefix: scilog-
        tag: ${{ steps.set_env.outputs.tag }}
        environment: ${{ steps.set_env.outputs.environment }}
        helm_chart: cron_chart
      secrets:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
        JSON_SECRETS: ${{ toJSON(secrets) }}
